version: 2
jobs:
  build_test:
    docker:
      - image: quay.io/token/go-build:v0.3.7
    working_directory: /home/circleci/github.com/tokencard/contracts
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "go.sum" }}
      - run:
          name: "Setup custom environment variables"
          command: |
            echo "export GO111MODULE=on" >> $BASH_ENV # Redirect MY_ENV_VAR into $BASH_ENV
      - run: go mod vendor
      - run:
          command: go run github.com/onsi/ginkgo/ginkgo -r ./test/...
          no_output_timeout: 30m

      - save_cache:
          key: vendor-{{ checksum "go.sum" }}
          paths:
            - "vendor"

  build_check:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: /home/circleci/github.com/tokencard/contracts
    steps:
      - checkout
      - restore_cache:
          keys:
            - vendor-{{ checksum "go.sum" }}
      - run: ./build.sh
      - run: '[[ -z $(git status -uno --porcelain) ]] || (git status ; echo "Please run ./build.sh before committing changes!"; exit 1)'

  mythril:
    docker:
      - image: mythril/myth:latest
    working_directory: /tmp/contracts
    parallelism: 6
    steps:
      - checkout
      - run:
          working_directory: contracts
          command: |
            if [[ "${CIRCLE_NODE_INDEX}" == 0 ]]; then
              myth analyze --solv=0.5.15 ./oracle.sol --execution-timeout=900
            fi
          no_output_timeout: 20m
      - run:
          working_directory: contracts
          command: |
            if [[ "${CIRCLE_NODE_INDEX}" == 1 ]]; then
              myth analyze --solv=0.5.15 ./wallet.sol --execution-timeout=900
            fi
          no_output_timeout: 20m
      - run:
          working_directory: contracts
          command: |
            if [[ "${CIRCLE_NODE_INDEX}" == 2 ]]; then
              myth analyze --solv=0.5.15 ./holder.sol --execution-timeout=900
            fi
          no_output_timeout: 20m
      - run:
          working_directory: contracts
          command: |
            if [[ "${CIRCLE_NODE_INDEX}" == 3 ]]; then
              myth analyze --solv=0.5.15 ./licence.sol --execution-timeout=900
            fi
          no_output_timeout: 20m
      - run:
          working_directory: contracts
          command: |
            if [[ "${CIRCLE_NODE_INDEX}" == 4 ]]; then
              myth analyze --solv=0.5.15 ./tokenWhitelist.sol --execution-timeout=900
            fi
          no_output_timeout: 20m
      - run:
          working_directory: contracts
          command: |
            if [[ "${CIRCLE_NODE_INDEX}" == 5 ]]; then
              myth analyze --solv=0.5.15 ./walletDeployer.sol --execution-timeout=900
            fi
          no_output_timeout: 20m

  slither:
    docker:
      - image: trailofbits/eth-security-toolbox:latest
    working_directory: /tmp/contracts
    steps:
      - run: sudo -n apt-get update && sudo -n apt-get install -y openssh-client
      - checkout
      - run:
          command: solc-select 0.5.15
      - run:
          working_directory: slither
          command: |
            slither ../contracts/wallet.sol ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 5m
      - run:
          working_directory: slither
          command: |
            slither ../contracts/oracle.sol ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 5m
      - run:
          working_directory: slither
          command: |
            slither ../contracts/licence.sol ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 5m
      - run:
          working_directory: slither
          command: |
            slither ../contracts/holder.sol ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 5m
      - run:
          working_directory: slither
          command: |
            slither ../contracts/tokenWhitelist.sol ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 5m
      - run:
          working_directory: slither
          command: |
            slither ../contracts/walletDeployer.sol ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 5m
      - run:
          command: test ! $FAILED

  echidna:
    docker:
      - image: trailofbits/eth-security-toolbox:latest
    working_directory: /tmp/contracts
    steps:
      - checkout
      - run:
          command: solc-select 0.5.15
      - run:
          command: |
            slither-flat --convert-external contracts/wallet.sol &&
            echidna-test echidna/addressWhitelist.sol --config echidna/addressWhitelist.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            slither-flat --convert-external contracts/controller.sol &&
            echidna-test echidna/controller.sol --config echidna/controller.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            echidna-test echidna/date.sol --config echidna/date.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            echidna-test echidna/ecRecover.sol --config echidna/ecRecover.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            echidna-test echidna/ecRecover.sol --config echidna/ecRecover.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            echidna-test echidna/gasTopUpLimit.sol --config echidna/gasTopUpLimit.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            echidna-test echidna/ownable.sol --config echidna/ownable.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            echidna-test echidna/parseJson.sol --config echidna/parseJson.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            echidna-test echidna/spendLimit.sol --config echidna/spendLimit.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: |
            echidna-test echidna/stringProps.sol --config echidna/stringProps.yaml TEST ||
            echo "export FAILED=true" >> $BASH_ENV
          no_output_timeout: 20m
      - run:
          command: test ! $FAILED

workflows:
  version: 2
  build_deploy:
    jobs:
      - build_test:
          filters:
            tags:
              ignore: ""
      - build_check:
          requires:
            - build_test
          filters:
            tags:
              ignore: ""
      - mythril:
          filters:
            tags:
              ignore: ""
      - slither:
          filters:
            tags:
              ignore: ""
 # - echidna:
 #     filters:
 #       tags:
 #         ignore: ""
